# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    name: Fetch daily amount
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git pull
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm install canvas
    - run: npm rebuild
    - run: node index.js
    - name: Add & Commit
      uses: EndBug/add-and-commit@v5.3.0
      with:
        author_name: Thanura Nadun
        author_email: nadunnew@gmail.com
        message: 'Daily Update'
        add: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}